### ISSUE TITLE
[BUG] Shipping address is not defined in Stripe

### ISSUE THREAD

**Issue by whiteagle3k** [juspay/hyperswitch-woocommerce-plugin#2]
Since las update (v106) of HS the plugin is not working with stripe, the response is 400 shipping address is missing, while it is being supplied.

**Comment by vsrivatsa-edinburgh** [comment]
Shipping and Billing address is passed in the Update Payment Intent payload, but due to amount validation failure on the backend it is failing.
https://github.com/juspay/hyperswitch/pull/3116 fixes this
